# Generated by Django 4.2.7 on 2023-11-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_grada', models.CharField(max_length=60, unique=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('drzava', models.CharField(max_length=30)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Gradovi',
            },
        ),
    ]
