# Generated by Django 4.2.7 on 2023-11-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grad',
            name='drzava',
            field=models.CharField(max_length=30, verbose_name='Država'),
        ),
        migrations.AlterField(
            model_name='grad',
            name='ime_grada',
            field=models.CharField(max_length=60, unique=True, verbose_name='Grad'),
        ),
        migrations.AlterField(
            model_name='grad',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Geo. širina'),
        ),
        migrations.AlterField(
            model_name='grad',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Geo. dužina'),
        ),
        migrations.AlterField(
            model_name='grad',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Poštanski broj'),
        ),
        migrations.CreateModel(
            name='GradskaCetvrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.IntegerField(max_length=60, verbose_name='Broj četvrti')),
                ('ime', models.CharField(max_length=60, verbose_name='Naziv')),
                ('grad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.grad', verbose_name='Grad')),
            ],
        ),
    ]
