# Generated by Django 4.2.7 on 2023-11-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_grad_drzava_alter_grad_ime_grada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradskacetvrt',
            name='broj',
            field=models.IntegerField(verbose_name='Broj četvrti'),
        ),
    ]
