# Generated by Django 4.2.7 on 2023-11-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_gradskacetvrt_options_mjesniodbor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prostor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=60, unique=True, verbose_name='Naziv')),
            ],
        ),
        migrations.RemoveField(
            model_name='gradskacetvrt',
            name='broj',
        ),
        migrations.AddField(
            model_name='mjesniodbor',
            name='broj',
            field=models.IntegerField(default=1, verbose_name='Broj četvrti'),
            preserve_default=False,
        ),
    ]
