# Generated by Django 4.2.7 on 2023-11-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_prostor_remove_gradskacetvrt_broj_mjesniodbor_broj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grad',
            name='ime_grada',
            field=models.CharField(max_length=60, verbose_name='Grad'),
        ),
    ]
