# Generated by Django 4.2.7 on 2023-11-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_tipprostora_alter_prostor_options_prostor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prostor',
            name='ime',
            field=models.CharField(max_length=60, verbose_name='Naziv'),
        ),
        migrations.AlterField(
            model_name='prostor',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='slike', verbose_name='Slike'),
        ),
        migrations.AlterField(
            model_name='prostor',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='slike', verbose_name='Slike'),
        ),
        migrations.AlterField(
            model_name='prostor',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='slike', verbose_name='Slike'),
        ),
    ]
