# Generated by Django 4.2.7 on 2023-11-25 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_prostor_ime_alter_prostor_img2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_prijavitelja', models.CharField(blank=True, choices=[('', ''), ('Fizička osoba', 'Fizička osoba'), ('Neprofitna udruga', 'Neprofitna udruga'), ('Pravna osoba', 'Pravna osoba'), ('Ostalo', 'Ostalo')], max_length=50, null=True, verbose_name='Vrsta prijavitelja')),
                ('naziv', models.CharField(max_length=60, verbose_name='Ime i prezime (za fizičke osobe) \nili naziv društva (za pravne osobe)')),
                ('sjediste', models.CharField(max_length=120, verbose_name='Prebivalište (za fizičke osobe) \nili sjedište (za pravne osobe)')),
                ('zastupnik', models.CharField(max_length=60, verbose_name='Ime i prezime osobe ovlaštene za zastupanje (samo za pravne osobe)')),
                ('oib_mbs', models.CharField(max_length=60, verbose_name='OIB ili MBS (za pravne osobe)')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('opis_aktivnosti', models.CharField(max_length=120, verbose_name='Opis aktivnosti koja bi se obavljala u prostoru')),
                ('datum', models.DateField(default=datetime.date(2023, 11, 25))),
                ('vrijeme_pocetak', models.TimeField()),
                ('vrijeme_kraj', models.TimeField()),
                ('napomena', models.CharField(max_length=120, verbose_name='Napomena')),
                ('status', models.BooleanField(default=False)),
                ('prilog1', models.FileField(blank=True, upload_to='prilozi', verbose_name='Prilog 1')),
                ('prilog2', models.FileField(blank=True, upload_to='prilozi', verbose_name='Prilog 2')),
                ('prilog3', models.FileField(blank=True, upload_to='prilozi', verbose_name='Prilog 3')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('gradska_cetvrt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.gradskacetvrt', verbose_name='Gradska četvrt')),
                ('mjesni_odbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.mjesniodbor', verbose_name='Mjesni odbor')),
                ('prostor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.prostor', verbose_name='Prostor')),
            ],
            options={
                'verbose_name_plural': 'Rezervacije',
            },
        ),
    ]
