# Generated by Django 4.2.7 on 2023-11-25 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0010_rezervacija'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predsjednik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=60, verbose_name='Ime i Prezime')),
                ('funkcija', models.CharField(max_length=60, verbose_name='Funkcija')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('mjesni_odbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.mjesniodbor', verbose_name='Mjesni odbor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name_plural': 'Predsjednici',
            },
        ),
    ]
